server:
  port: ${WEB_PORT:8082}
  error:
    whitelabel:
          enabled: false

spring:
  application:
    name: talkpick-batch
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  web:
    resources:
      add-mappings: false
log:
  rolling:
    directory: logs
    file-name: talkpick-batch.log
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [TraceId: %X{traceId:-no-trace}] - %msg%n"
    max-history: 30
    total-size-cap: 10MB
decorator:
  datasource:
    p6spy:
      enable-logging: true
