name: "✨ Epic"
description: 큰 기능(에픽) 카드 – 하위 사용자 스토리를 모으는 부모 이슈
title: "[Epic] "
labels: [epic]
assignees: []

body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 목표(Problem / Goal)
      description: "이 에픽이 해결하려는 문제 또는 달성할 목표를 간략히 서술하세요."
      placeholder: |
        예) “외부 인증 없이도 원‑클릭 로그인 기능을 제공하여, 신규 유저 유입 장벽을 낮춘다.”
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 📝 배경 / 맥락
      description: 설계 근거, 관련 문서·링크 등이 있으면 적어 주세요.
      placeholder: |
        - Figma UX 흐름: https://figma.com/…
        - OAuth 2.0 Sequence 다이어그램
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: 📋 범위 – 예상 하위 작업 체크리스트
      description: "*하위 Issue 를 추가하면 자동으로 갱신되므로 초안만 작성해도 됩니다.*"
      placeholder: |
        - [ ] UI 버튼 디자인
        - [ ] OAuth 동의 화면 호출
        - [ ] 신규 사용자 DB 저장
      render: markdown
    validations:
      required: false

  - type: textarea
    id: dod
    attributes:
      label: ✅ 완료 기준(Definition of Done)
      description: "에픽이 ‘Done’ 으로 이동되기 위한 최소 조건을 적으세요."
      placeholder: |
        - 모든 하위 Issue 완료
        - Dev/Staging 배포 확인
        - 릴리스 노트 작성
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        🔗 **하위 이슈 연결 방법**  
        - 새 이슈를 만들 때 본문 맨 위에 `parent: #<이 Epic 번호>`를 쓰거나  
        - Projects 보드에서 “Add child issue” 버튼을 누르세요.