name: "🛠️ Tech Debt / Refactor"
description: 리팩터링·성능 개선·보안 패치 등 기술 부채 상환 이슈
title: "[Tech Debt] "
labels: [tech-debt]
assignees: []

body:
  - type: textarea
    id: area
    attributes:
      label: 📍 개선 대상(모듈·파일·클래스)
      placeholder: |
        예) NewsController 의 300라인 이상 메소드 분리
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🔎 현재 문제점
      description: "왜 부채가 되었는지, 어떤 위험·불편이 있는지 작성해 주세요."
      placeholder: |
        - 메소드 길이가 200라인을 넘어 가독성이 떨어집니다.
        - 동일 로직이 Service 레이어에도 중복되어 유지보수가 어렵습니다.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 💡 개선 방안(선택)
      placeholder: |
        - 메소드 분리 + 공통 로직 Utility 이동
        - 단위 테스트 추가
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: ⏰ 우선순위
      description: "해결 시기를 가늠할 수 있도록 심각도를 선택해 주세요."
      options:
        - high (즉시 상환: 다음 스프린트 포함)
        - medium (2~3 스프린트 내)
        - low (시간 날 때)
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: 기대 효과(복수 선택)
      options:
        - label: 읽기 쉬운 코드
        - label: 성능 개선
        - label: 버그 위험 감소
        - label: 보안 강화
        - label: 테스트 용이성 향상
        - label: 기타 (추가 건의)