name: "🗂️ 사용자 스토리"
description: 개발 작업 카드 (INVEST 형식)
title: ""
labels: []
assignees: []

body:
  - type: textarea
    id: story
    attributes:
      label: 사용자 스토리
      description: "형식: **[역할]**로서 **[목표]**를 하고 싶다. 그 결과 **[이점]**을 얻는다."
      placeholder: |
        예) 방문자로서 키워드로 뉴스를 검색하고 싶다. 그 결과 관련 기사를 빠르게 찾을 수 있다.
    validations:
      required: true

  - type: textarea
    id: ac
    attributes:
      label: 수락 기준(Acceptance Criteria)
      description: "동작 완료 조건 2~5개 (가능하면 Given‑When‑Then)."
      placeholder: |
        - [ ] 검색 결과는 0.5초 이내 반환된다
        - [ ] 결과가 없으면 '결과가 없습니다' 토스트가 표시된다
    validations:
      required: true
      
  - type: checkboxes
    id: dor
    attributes:
      label: Definition of Ready 체크
      options:
        - label: 설명·목표가 명확하다
        - label: 수락 기준이 작성되었다